import type { FeatureFlag, Experiment, AuditEntry } from './types';

// 15 flags across 3 environments
export const mockFlags: FeatureFlag[] = [
  {
    id: 'flag-001',
    key: 'new-dashboard-ui',
    name: 'New Dashboard UI',
    description: 'Redesigned dashboard with improved analytics widgets and real-time metrics.',
    type: 'boolean',
    status: 'active',
    enabled: true,
    environments: {
      development: { enabled: true, rolloutPercentage: 100 },
      staging: { enabled: true, rolloutPercentage: 100 },
      production: { enabled: true, rolloutPercentage: 45 },
    },
    targetingRules: [
      { id: 'r1', attribute: 'user_id', operator: 'in_list', value: 'usr_001,usr_002,usr_003' },
      { id: 'r2', attribute: 'plan', operator: 'equals', value: 'enterprise' },
    ],
    tags: ['frontend', 'dashboard'],
    owner: 'Sarah Chen',
    createdAt: '2025-11-15T10:30:00Z',
    updatedAt: '2026-03-25T14:20:00Z',
    lastEvaluatedAt: '2026-03-27T09:15:00Z',
    evaluationCount: 284310,
    killSwitchActive: false,
    lastKilledAt: null,
  },
  {
    id: 'flag-002',
    key: 'checkout-v2',
    name: 'Checkout Flow V2',
    description: 'Streamlined checkout process with fewer steps and inline validation.',
    type: 'boolean',
    status: 'active',
    enabled: true,
    environments: {
      development: { enabled: true, rolloutPercentage: 100 },
      staging: { enabled: true, rolloutPercentage: 100 },
      production: { enabled: true, rolloutPercentage: 72 },
    },
    targetingRules: [
      { id: 'r3', attribute: 'country', operator: 'in_list', value: 'US,CA,GB' },
    ],
    tags: ['checkout', 'conversion'],
    owner: 'Marcus Johnson',
    createdAt: '2025-12-01T08:00:00Z',
    updatedAt: '2026-03-20T11:30:00Z',
    lastEvaluatedAt: '2026-03-27T09:14:55Z',
    evaluationCount: 512040,
    killSwitchActive: false,
    lastKilledAt: null,
  },
  {
    id: 'flag-003',
    key: 'dark-mode',
    name: 'Dark Mode',
    description: 'System-wide dark mode toggle for all user interfaces.',
    type: 'boolean',
    status: 'active',
    enabled: true,
    environments: {
      development: { enabled: true, rolloutPercentage: 100 },
      staging: { enabled: true, rolloutPercentage: 100 },
      production: { enabled: true, rolloutPercentage: 100 },
    },
    targetingRules: [],
    tags: ['frontend', 'theme'],
    owner: 'Sarah Chen',
    createdAt: '2025-08-20T14:00:00Z',
    updatedAt: '2025-10-15T09:00:00Z',
    lastEvaluatedAt: '2026-03-27T09:15:01Z',
    evaluationCount: 1284030,
    killSwitchActive: false,
    lastKilledAt: null,
  },
  {
    id: 'flag-004',
    key: 'ai-recommendations',
    name: 'AI Product Recommendations',
    description: 'ML-powered product recommendation engine using collaborative filtering.',
    type: 'boolean',
    status: 'active',
    enabled: true,
    environments: {
      development: { enabled: true, rolloutPercentage: 100 },
      staging: { enabled: true, rolloutPercentage: 80 },
      production: { enabled: true, rolloutPercentage: 25 },
    },
    targetingRules: [
      { id: 'r4', attribute: 'plan', operator: 'equals', value: 'pro' },
      { id: 'r5', attribute: 'plan', operator: 'equals', value: 'enterprise' },
    ],
    tags: ['ml', 'recommendations', 'backend'],
    owner: 'Priya Patel',
    createdAt: '2026-01-10T12:00:00Z',
    updatedAt: '2026-03-26T16:45:00Z',
    lastEvaluatedAt: '2026-03-27T09:14:58Z',
    evaluationCount: 98200,
    killSwitchActive: false,
    lastKilledAt: null,
  },
  {
    id: 'flag-005',
    key: 'search-v3',
    name: 'Search Engine V3',
    description: 'Elasticsearch-based search with fuzzy matching, faceted results, and auto-suggestions.',
    type: 'boolean',
    status: 'stale',
    enabled: true,
    environments: {
      development: { enabled: true, rolloutPercentage: 100 },
      staging: { enabled: true, rolloutPercentage: 100 },
      production: { enabled: true, rolloutPercentage: 100 },
    },
    targetingRules: [],
    tags: ['search', 'backend'],
    owner: 'Marcus Johnson',
    createdAt: '2025-06-01T09:00:00Z',
    updatedAt: '2025-09-15T14:30:00Z',
    lastEvaluatedAt: '2026-01-10T08:00:00Z',
    evaluationCount: 2100500,
    killSwitchActive: false,
    lastKilledAt: null,
  },
  {
    id: 'flag-006',
    key: 'notification-center',
    name: 'Notification Center',
    description: 'Centralized notification hub with real-time WebSocket updates.',
    type: 'boolean',
    status: 'active',
    enabled: true,
    environments: {
      development: { enabled: true, rolloutPercentage: 100 },
      staging: { enabled: true, rolloutPercentage: 100 },
      production: { enabled: true, rolloutPercentage: 60 },
    },
    targetingRules: [
      { id: 'r6', attribute: 'email', operator: 'ends_with', value: '@company.com' },
    ],
    tags: ['notifications', 'frontend'],
    owner: 'Alex Rivera',
    createdAt: '2026-02-01T10:00:00Z',
    updatedAt: '2026-03-24T13:15:00Z',
    lastEvaluatedAt: '2026-03-27T09:14:50Z',
    evaluationCount: 45600,
    killSwitchActive: false,
    lastKilledAt: null,
  },
  {
    id: 'flag-007',
    key: 'api-rate-limit-v2',
    name: 'API Rate Limit V2',
    description: 'Token bucket rate limiting with per-plan quotas and burst allowance.',
    type: 'number',
    status: 'active',
    enabled: true,
    environments: {
      development: { enabled: false, rolloutPercentage: 0 },
      staging: { enabled: true, rolloutPercentage: 100 },
      production: { enabled: true, rolloutPercentage: 100 },
    },
    targetingRules: [
      { id: 'r7', attribute: 'plan', operator: 'equals', value: 'free', percentage: 100 },
    ],
    tags: ['api', 'security', 'backend'],
    owner: 'James Kim',
    createdAt: '2026-01-20T15:00:00Z',
    updatedAt: '2026-03-22T10:00:00Z',
    lastEvaluatedAt: '2026-03-27T09:15:02Z',
    evaluationCount: 890300,
    killSwitchActive: false,
    lastKilledAt: null,
  },
  {
    id: 'flag-008',
    key: 'payment-stripe-v3',
    name: 'Stripe Payment V3',
    description: 'Updated Stripe integration with Payment Intents API and 3D Secure support.',
    type: 'boolean',
    status: 'deprecated',
    enabled: false,
    environments: {
      development: { enabled: false, rolloutPercentage: 0 },
      staging: { enabled: false, rolloutPercentage: 0 },
      production: { enabled: false, rolloutPercentage: 0 },
    },
    targetingRules: [],
    tags: ['payments', 'backend'],
    owner: 'Marcus Johnson',
    createdAt: '2025-03-10T11:00:00Z',
    updatedAt: '2025-12-01T16:00:00Z',
    lastEvaluatedAt: '2025-11-30T23:59:00Z',
    evaluationCount: 3450200,
    killSwitchActive: false,
    lastKilledAt: '2025-11-28T14:32:00Z',
  },
  {
    id: 'flag-009',
    key: 'onboarding-wizard-v2',
    name: 'Onboarding Wizard V2',
    description: 'Interactive step-by-step onboarding with progress tracking and skip options.',
    type: 'boolean',
    status: 'active',
    enabled: true,
    environments: {
      development: { enabled: true, rolloutPercentage: 100 },
      staging: { enabled: true, rolloutPercentage: 100 },
      production: { enabled: true, rolloutPercentage: 35 },
    },
    targetingRules: [
      { id: 'r8', attribute: 'account_age_days', operator: 'equals', value: '0' },
    ],
    tags: ['onboarding', 'frontend'],
    owner: 'Sarah Chen',
    createdAt: '2026-02-15T09:00:00Z',
    updatedAt: '2026-03-26T17:30:00Z',
    lastEvaluatedAt: '2026-03-27T09:14:45Z',
    evaluationCount: 12400,
    killSwitchActive: false,
    lastKilledAt: null,
  },
  {
    id: 'flag-010',
    key: 'export-pdf',
    name: 'PDF Export',
    description: 'Server-side PDF generation for reports and invoices using Puppeteer.',
    type: 'boolean',
    status: 'archived',
    enabled: false,
    environments: {
      development: { enabled: false, rolloutPercentage: 0 },
      staging: { enabled: false, rolloutPercentage: 0 },
      production: { enabled: false, rolloutPercentage: 0 },
    },
    targetingRules: [],
    tags: ['export', 'backend'],
    owner: 'James Kim',
    createdAt: '2024-11-01T08:00:00Z',
    updatedAt: '2025-06-01T12:00:00Z',
    lastEvaluatedAt: '2025-05-15T10:00:00Z',
    evaluationCount: 560000,
    killSwitchActive: false,
    lastKilledAt: null,
  },
  {
    id: 'flag-011',
    key: 'real-time-collab',
    name: 'Real-Time Collaboration',
    description: 'CRDT-based collaborative editing with presence indicators and cursor sharing.',
    type: 'boolean',
    status: 'draft',
    enabled: false,
    environments: {
      development: { enabled: true, rolloutPercentage: 100 },
      staging: { enabled: false, rolloutPercentage: 0 },
      production: { enabled: false, rolloutPercentage: 0 },
    },
    targetingRules: [],
    tags: ['collaboration', 'frontend', 'experimental'],
    owner: 'Alex Rivera',
    createdAt: '2026-03-20T10:00:00Z',
    updatedAt: '2026-03-25T11:00:00Z',
    lastEvaluatedAt: null,
    evaluationCount: 0,
    killSwitchActive: false,
    lastKilledAt: null,
  },
  {
    id: 'flag-012',
    key: 'pricing-page-redesign',
    name: 'Pricing Page Redesign',
    description: 'New pricing page with annual/monthly toggle, comparison table, and FAQ section.',
    type: 'boolean',
    status: 'active',
    enabled: true,
    environments: {
      development: { enabled: true, rolloutPercentage: 100 },
      staging: { enabled: true, rolloutPercentage: 100 },
      production: { enabled: true, rolloutPercentage: 50 },
    },
    targetingRules: [
      { id: 'r9', attribute: 'country', operator: 'in_list', value: 'US,CA' },
    ],
    tags: ['pricing', 'frontend', 'conversion'],
    owner: 'Priya Patel',
    createdAt: '2026-02-28T14:00:00Z',
    updatedAt: '2026-03-27T08:00:00Z',
    lastEvaluatedAt: '2026-03-27T09:14:40Z',
    evaluationCount: 67800,
    killSwitchActive: false,
    lastKilledAt: null,
  },
  {
    id: 'flag-013',
    key: 'bulk-import',
    name: 'Bulk Data Import',
    description: 'CSV and JSON bulk import with progress tracking, validation, and rollback.',
    type: 'boolean',
    status: 'active',
    enabled: true,
    environments: {
      development: { enabled: true, rolloutPercentage: 100 },
      staging: { enabled: true, rolloutPercentage: 100 },
      production: { enabled: true, rolloutPercentage: 90 },
    },
    targetingRules: [
      { id: 'r10', attribute: 'plan', operator: 'not_equals', value: 'free' },
    ],
    tags: ['data', 'backend'],
    owner: 'James Kim',
    createdAt: '2026-01-05T16:00:00Z',
    updatedAt: '2026-03-15T09:00:00Z',
    lastEvaluatedAt: '2026-03-27T09:14:30Z',
    evaluationCount: 23400,
    killSwitchActive: false,
    lastKilledAt: null,
  },
  {
    id: 'flag-014',
    key: 'mobile-app-banner',
    name: 'Mobile App Download Banner',
    description: 'Smart banner prompting mobile web users to download the native app.',
    type: 'string',
    status: 'stale',
    enabled: true,
    environments: {
      development: { enabled: true, rolloutPercentage: 100 },
      staging: { enabled: true, rolloutPercentage: 100 },
      production: { enabled: true, rolloutPercentage: 100 },
    },
    targetingRules: [
      { id: 'r11', attribute: 'device', operator: 'in_list', value: 'ios,android' },
    ],
    tags: ['mobile', 'marketing'],
    owner: 'Priya Patel',
    createdAt: '2025-07-15T10:00:00Z',
    updatedAt: '2025-11-01T08:00:00Z',
    lastEvaluatedAt: '2026-01-05T12:00:00Z',
    evaluationCount: 890000,
    killSwitchActive: false,
    lastKilledAt: null,
  },
  {
    id: 'flag-015',
    key: 'webhooks-v2',
    name: 'Webhooks V2',
    description: 'Redesigned webhook system with retry policies, payload signing, and delivery logs.',
    type: 'boolean',
    status: 'active',
    enabled: true,
    environments: {
      development: { enabled: true, rolloutPercentage: 100 },
      staging: { enabled: true, rolloutPercentage: 50 },
      production: { enabled: true, rolloutPercentage: 15 },
    },
    targetingRules: [
      { id: 'r12', attribute: 'plan', operator: 'equals', value: 'enterprise' },
    ],
    tags: ['webhooks', 'api', 'backend'],
    owner: 'Alex Rivera',
    createdAt: '2026-03-01T11:00:00Z',
    updatedAt: '2026-03-27T07:30:00Z',
    lastEvaluatedAt: '2026-03-27T09:14:20Z',
    evaluationCount: 5600,
    killSwitchActive: false,
    lastKilledAt: null,
  },
];

export const mockExperiments: Experiment[] = [
  {
    id: 'exp-001',
    flagId: 'flag-001',
    name: 'Dashboard UI Conversion Test',
    status: 'running',
    variants: [
      { id: 'v1', name: 'Control', description: 'Current dashboard design', allocation: 50, conversions: 1240, impressions: 12400, conversionRate: 10.0 },
      { id: 'v2', name: 'Treatment', description: 'New dashboard with analytics widgets', allocation: 50, conversions: 1488, impressions: 12400, conversionRate: 12.0 },
    ],
    primaryMetric: 'dashboard_engagement',
    baselineRate: 10.0,
    mde: 2.0,
    significanceLevel: 0.05,
    power: 0.8,
    requiredSampleSize: 39240,
    currentSampleSize: 24800,
    startedAt: '2026-03-15T00:00:00Z',
    completedAt: null,
  },
  {
    id: 'exp-002',
    flagId: 'flag-002',
    name: 'Checkout Flow Conversion',
    status: 'running',
    variants: [
      { id: 'v3', name: 'Control (3-step)', description: 'Current 3-step checkout', allocation: 50, conversions: 3200, impressions: 40000, conversionRate: 8.0 },
      { id: 'v4', name: 'Treatment (1-step)', description: 'Single-page checkout', allocation: 50, conversions: 3720, impressions: 40000, conversionRate: 9.3 },
    ],
    primaryMetric: 'checkout_completion',
    baselineRate: 8.0,
    mde: 1.0,
    significanceLevel: 0.05,
    power: 0.8,
    requiredSampleSize: 125000,
    currentSampleSize: 80000,
    startedAt: '2026-03-01T00:00:00Z',
    completedAt: null,
  },
  {
    id: 'exp-003',
    flagId: 'flag-012',
    name: 'Pricing Page CTA Test',
    status: 'completed',
    variants: [
      { id: 'v5', name: 'Variant A', description: '"Start Free Trial" CTA', allocation: 50, conversions: 890, impressions: 15000, conversionRate: 5.93 },
      { id: 'v6', name: 'Variant B', description: '"Get Started Free" CTA', allocation: 50, conversions: 1020, impressions: 15000, conversionRate: 6.8 },
    ],
    primaryMetric: 'trial_signup',
    baselineRate: 5.93,
    mde: 1.0,
    significanceLevel: 0.05,
    power: 0.8,
    requiredSampleSize: 28000,
    currentSampleSize: 30000,
    startedAt: '2026-02-15T00:00:00Z',
    completedAt: '2026-03-10T00:00:00Z',
  },
];

const actors = [
  { id: 'u1', email: 'sarah.chen@company.com', name: 'Sarah Chen' },
  { id: 'u2', email: 'marcus.j@company.com', name: 'Marcus Johnson' },
  { id: 'u3', email: 'priya.p@company.com', name: 'Priya Patel' },
  { id: 'u4', email: 'alex.r@company.com', name: 'Alex Rivera' },
  { id: 'u5', email: 'james.k@company.com', name: 'James Kim' },
];

export const mockAuditLog: AuditEntry[] = [
  {
    id: 'audit-001',
    timestamp: '2026-03-27T09:00:00Z',
    actor: actors[0],
    action: 'rollout_changed',
    resourceType: 'flag',
    resourceId: 'flag-001',
    resourceName: 'New Dashboard UI',
    description: 'Changed production rollout from 40% to 45%',
    before: '40%',
    after: '45%',
    ipAddress: '192.168.1.100',
  },
  {
    id: 'audit-002',
    timestamp: '2026-03-27T08:00:00Z',
    actor: actors[2],
    action: 'updated',
    resourceType: 'flag',
    resourceId: 'flag-012',
    resourceName: 'Pricing Page Redesign',
    description: 'Updated targeting rules to include Canada',
    before: 'country in [US]',
    after: 'country in [US, CA]',
    ipAddress: '10.0.0.55',
  },
  {
    id: 'audit-003',
    timestamp: '2026-03-27T07:30:00Z',
    actor: actors[3],
    action: 'rollout_changed',
    resourceType: 'flag',
    resourceId: 'flag-015',
    resourceName: 'Webhooks V2',
    description: 'Increased staging rollout from 40% to 50%',
    before: '40%',
    after: '50%',
    ipAddress: '172.16.0.22',
  },
  {
    id: 'audit-004',
    timestamp: '2026-03-26T17:30:00Z',
    actor: actors[0],
    action: 'updated',
    resourceType: 'targeting_rule',
    resourceId: 'flag-009',
    resourceName: 'Onboarding Wizard V2',
    description: 'Added account_age_days targeting rule',
    before: 'No targeting rules',
    after: 'account_age_days equals 0',
    ipAddress: '192.168.1.100',
  },
  {
    id: 'audit-005',
    timestamp: '2026-03-26T16:45:00Z',
    actor: actors[2],
    action: 'rollout_changed',
    resourceType: 'flag',
    resourceId: 'flag-004',
    resourceName: 'AI Product Recommendations',
    description: 'Changed production rollout from 20% to 25%',
    before: '20%',
    after: '25%',
    ipAddress: '10.0.0.55',
  },
  {
    id: 'audit-006',
    timestamp: '2026-03-26T14:00:00Z',
    actor: actors[1],
    action: 'experiment_started',
    resourceType: 'experiment',
    resourceId: 'exp-002',
    resourceName: 'Checkout Flow Conversion',
    description: 'Started A/B test for checkout-v2 flag',
    ipAddress: '10.0.0.88',
  },
  {
    id: 'audit-007',
    timestamp: '2026-03-25T14:20:00Z',
    actor: actors[0],
    action: 'enabled',
    resourceType: 'flag',
    resourceId: 'flag-001',
    resourceName: 'New Dashboard UI',
    description: 'Enabled flag in production environment',
    before: 'disabled',
    after: 'enabled',
    ipAddress: '192.168.1.100',
  },
  {
    id: 'audit-008',
    timestamp: '2026-03-25T11:00:00Z',
    actor: actors[3],
    action: 'created',
    resourceType: 'flag',
    resourceId: 'flag-011',
    resourceName: 'Real-Time Collaboration',
    description: 'Created new flag real-time-collab (draft)',
    ipAddress: '172.16.0.22',
  },
  {
    id: 'audit-009',
    timestamp: '2026-03-24T13:15:00Z',
    actor: actors[3],
    action: 'rollout_changed',
    resourceType: 'flag',
    resourceId: 'flag-006',
    resourceName: 'Notification Center',
    description: 'Changed production rollout from 50% to 60%',
    before: '50%',
    after: '60%',
    ipAddress: '172.16.0.22',
  },
  {
    id: 'audit-010',
    timestamp: '2026-03-22T10:00:00Z',
    actor: actors[4],
    action: 'updated',
    resourceType: 'flag',
    resourceId: 'flag-007',
    resourceName: 'API Rate Limit V2',
    description: 'Updated rate limit configuration for free plan',
    before: '1000 req/min',
    after: '500 req/min',
    ipAddress: '10.0.0.33',
  },
  {
    id: 'audit-011',
    timestamp: '2026-03-20T10:00:00Z',
    actor: actors[3],
    action: 'created',
    resourceType: 'flag',
    resourceId: 'flag-011',
    resourceName: 'Real-Time Collaboration',
    description: 'Created flag real-time-collab',
    ipAddress: '172.16.0.22',
  },
  {
    id: 'audit-012',
    timestamp: '2026-03-15T09:00:00Z',
    actor: actors[4],
    action: 'rollout_changed',
    resourceType: 'flag',
    resourceId: 'flag-013',
    resourceName: 'Bulk Data Import',
    description: 'Increased production rollout from 80% to 90%',
    before: '80%',
    after: '90%',
    ipAddress: '10.0.0.33',
  },
  {
    id: 'audit-013',
    timestamp: '2026-03-10T00:00:00Z',
    actor: actors[2],
    action: 'experiment_stopped',
    resourceType: 'experiment',
    resourceId: 'exp-003',
    resourceName: 'Pricing Page CTA Test',
    description: 'Experiment completed - Variant B won with 6.8% conversion rate',
    ipAddress: '10.0.0.55',
  },
  {
    id: 'audit-014',
    timestamp: '2026-03-01T11:00:00Z',
    actor: actors[3],
    action: 'created',
    resourceType: 'flag',
    resourceId: 'flag-015',
    resourceName: 'Webhooks V2',
    description: 'Created flag webhooks-v2',
    ipAddress: '172.16.0.22',
  },
  {
    id: 'audit-015',
    timestamp: '2025-12-01T16:00:00Z',
    actor: actors[1],
    action: 'archived',
    resourceType: 'flag',
    resourceId: 'flag-008',
    resourceName: 'Stripe Payment V3',
    description: 'Deprecated flag - migrated to Stripe Payment V4',
    before: 'active',
    after: 'deprecated',
    ipAddress: '10.0.0.88',
  },
  {
    id: 'audit-016',
    timestamp: '2025-11-28T14:32:00Z',
    actor: actors[1],
    action: 'killed',
    resourceType: 'flag',
    resourceId: 'flag-008',
    resourceName: 'Stripe Payment V3',
    description: 'Emergency kill switch activated due to payment processing errors',
    before: 'enabled (72%)',
    after: 'killed (0%)',
    ipAddress: '10.0.0.88',
  },
];

export function getFlagById(id: string): FeatureFlag | undefined {
  return mockFlags.find((f) => f.id === id);
}

export function getExperimentsByFlagId(flagId: string): Experiment[] {
  return mockExperiments.filter((e) => e.flagId === flagId);
}

export function getAuditLogForFlag(flagId: string): AuditEntry[] {
  return mockAuditLog.filter((e) => e.resourceId === flagId);
}

export function estimateAffectedUsers(percentage: number): number {
  const totalUsers = 142500;
  return Math.round(totalUsers * (percentage / 100));
}
